name: pr-test
on: pull_request

env:
  CI: true
  SPRING_PROFILES_ACTIVE: ${{ secrets.SPRING_PROFILES_ACTIVE }}
  SERVER_PORT: ${{ secrets.SERVER_PORT }}
  SPRING_DATASOURCE_URL: ${{ secrets.SPRING_DATASOURCE_URL }}
  SPRING_DATASOURCE_USERNAME: ${{ secrets.SPRING_DATASOURCE_USERNAME }}
  SPRING_DATASOURCE_PASSWORD: ${{ secrets.SPRING_DATASOURCE_PASSWORD }}
  REDIS_HOST: ${{ secrets.REDIS_HOST }}
  JWT_SECRET_KEY: ${{ secrets.JWT_SECRET_KEY }}
  JWT_ACCESS_TIME: ${{ secrets.JWT_ACCESS_TIME }}
  JWT_REFRESH_TIME: ${{ secrets.JWT_REFRESH_TIME }}
  ENCRYPT_KEY: ${{ secrets.ENCRYPT_KEY }}

  SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}

jobs:
  pr-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@main

      - name: Start Redis
        uses: supercharge/redis-github-action@1.1.0
        with:
          redis-version: 6

      - name: Start Mysql Service
        run: |
          sudo /etc/init.d/mysql start
          mysql -e 'CREATE DATABASE shoppingtest;' -uroot -proot

      - name: Set up JDK 21
        uses: actions/setup-java@main
        with:
          java-version: '21'
          cache: 'gradle'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: 8.5

      - name: Run Test
        uses: gradle/gradle-build-action@v3
        with:
          gradle-version: wrapper
          arguments: test

      - name: send slack notification
        uses: 8398a7/action-slack@v3
        with:
          status: ${{ job.status }}
          fields: repo,commit,author,ref,workflow,job,took
          author_name: GitHub Actions
        if: always()



